version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: classe-iasdmr-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    # Se você precisar de um banco de dados, adicione aqui
    # depends_on:
    #   - mongodb
    volumes:
      - app-data:/app/data

# Definição de volumes para persistência de dados
volumes:
  app-data:
    driver: local